/*
 * This file was generated by the Gradle 'init' task.
 */

val ktorVersion: String by project
val sl4jVersion: String by project
val dl4jVersion: String by project

plugins {
    java
    `maven-publish`
    kotlin("jvm") version "1.5.31"
}


repositories {
    mavenCentral()
    maven {
        url = uri("https://maven.pkg.jetbrains.space/public/p/ktor/eap")
        name = "ktor-eap"
    }
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation( group ="org.json", name= "json", version = "20211205")
    implementation("net.sf.opencsv:opencsv:2.3")
    implementation("org.nd4j:nd4j-native-platform:1.0.0-beta7")
    implementation("org.deeplearning4j:deeplearning4j-core:$dl4jVersion")
    implementation("org.deeplearning4j:deeplearning4j-nlp:$dl4jVersion")

    implementation("ch.qos.logback:logback-classic:1.2.6")
    implementation("io.ktor:ktor-server-core:2.0.0-eap-256")
    implementation("io.ktor:ktor-server-netty:2.0.0-eap-256")
    implementation("org.junit.jupiter:junit-jupiter:5.7.0")
}

group = "dev.isteam"
version = "1.0-SNAPSHOT"
description = rootProject.name
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
